### ISSUE TITLE
Grape new project with ORM flag  is not working

### ISSUE THREAD

**Issue by nmenag** [LeFnord/grape-starter#24]
I am using the instrutions give for the Readme,  is not generating the files, is not generating the `database.yml`  and another files: 

```
├── .config
├── config
│   …
│   ├── database.yml
│   └── initializers
│       └── database.rb
…
├── db
│   └── migrations
…
```

Command:

`grape-starter new new_project --orm=sequel`

Grape-starter version: `grape-starter version 1.2.4`

**Comment by LeFnord** [comment]
yeap … the options must be set before the name
```shell
grape-starter new -o sequel new_project
```
