### ISSUE TITLE
Dependency missing

### ISSUE THREAD

**Issue by terry90** [LeFnord/grape-starter#6]
Hello,

You should add awesome_print in our dependencies to avoid crash during the generation.

**Comment by LeFnord** [comment]
Hi @terry90 … it is, see: [Gemfile#L8](https://github.com/LeFnord/grape-starter/blob/master/Gemfile#L8), but feel welcome to change it

**Comment by terry90** [comment]
Oh yes indeed, sorry for that. I opened this issue because it crashed for me due to awesome_print when I tried to create a new project. I had to `gem install` manually. Not a big deal, though

**Comment by LeFnord** [comment]
solved with #7
