### ISSUE TITLE
Change the way the documentation is mounted

### ISSUE THREAD

**Issue by terry90** [LeFnord/grape-starter#8]
Put it accessible at a configurable path, mounted along the generated API

**Comment by LeFnord** [comment]
what did you mean with it? think, I didn't understand it :(

**Comment by terry90** [comment]
I think we can add a route pointing to the template instead of an mounted application, especially it is accessible with every non used path like `api.test.com/oijfdsof`

We can create a file `documentation.rb` to be mounted `mount Something::Documentation`, easy to change or unmount without deleting everything, just have to comment this line.

What do you think ?

**Comment by LeFnord** [comment]
mmh … an route endpoint for the documentation still exists, it comes with [grape-swagger](https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/doc_methods.rb#L66) in …
think, to change this [call](https://github.com/LeFnord/grape-starter/blob/master/template/config/application.rb#L48-L54) to something like this:
```ruby
def call(env)
  if env['REQUEST_PATH'].include?('oapi')
    DocApp.new.call(env)
  else
    Api::Base.call(env)
  end
end
```
can do what you mean, or?

**Comment by terry90** [comment]
Indeed, we can keep this like this. :+1:
